name: Rust CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libdbus-1-dev pkg-config
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
